server:
  port: 8091

spring:
  application:
    name: rococo-userdata
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: test
    password: secret
    url: 'jdbc:mysql://localhost:3306/rococo-userdata?serverTimezone=UTC&createDatabaseIfNotExist=true'
  flyway:
    enabled: true
    repair-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rococo-userdata
    locations: classpath:db/migration/rococo-userdata
    table: flyway_history_userdata
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false

logging:
  file:
    path: .logs/rococo-userdata/
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.springframework.web: INFO
