server:
  port: 8090
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

logging:
  file:
    path: .logs/rococo-gateway/
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

grpc:
  client:
    grpcUserdataClient:
      address: 'static://localhost:8091'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      max-inbound-message-size: 50MB
      max-outbound-message-size: 50MB
    grpcArtistClient:
      address: 'static://localhost:8092'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      max-inbound-message-size: 50MB
      max-outbound-message-size: 50MB
    grpcMuseumClient:
      address: 'static://localhost:8093'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      max-inbound-message-size: 50MB
      max-outbound-message-size: 50MB
    grpcGeoClient:
      address: 'static://localhost:8094'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      max-inbound-message-size: 50MB
      max-outbound-message-size: 50MB
    grpcPaintingClient:
      address: 'static://localhost:8095'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 50MB
      max-outbound-message-size: 50MB

rococo-front:
  base-uri: 'http://127.0.0.1:3000'