services:
  rococo-all-db:
    container_name: rococo-all-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=GMT+3
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    networks:
      - rococo-network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - rococo-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - 9092:9092
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - rococo-network

  auth.rococo.dc:
    container_name: auth.rococo.dc
    image: ${PREFIX}/rococo-auth-docker:latest
    ports:
      - 9000:9000
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - rococo-network

  gateway.rococo.dc:
    container_name: gateway.rococo.dc
    image: ${PREFIX}/rococo-gateway-docker:latest
    ports:
      - 8090:8090
    healthcheck:
      test: "wget --spider http://localhost:8090/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
      museum.rococo.dc:
        condition: service_healthy
      artist.rococo.dc:
        condition: service_healthy
      painting.rococo.dc:
        condition: service_healthy
      geo.rococo.dc:
        condition: service_healthy
      userdata.rococo.dc:
        condition: service_healthy
    networks:
      - rococo-network

  geo.rococo.dc:
    container_name: geo.rococo.dc
    image: ${PREFIX}/rococo-geo-docker:latest
    ports:
      - 8094:8094
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 5s
      timeout: 5s
      retries: 6
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  artist.rococo.dc:
    container_name: artist.rococo.dc
    image: ${PREFIX}/rococo-artist-docker:latest
    ports:
      - 8092:8092
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 15s
      timeout: 5s
      retries: 6
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  userdata.rococo.dc:
    container_name: userdata.rococo.dc
    image: ${PREFIX}/rococo-userdata-docker:latest
    ports:
      - 8091:8091
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  museum.rococo.dc:
    container_name: museum.rococo.dc
    environment:
      - LOGGING_LEVEL_GRPC=DEBUG
      - LOGGING_LEVEL_ROOT=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
      - LOGGING_LEVEL_GURU_QA=DEBUG
    image: ${PREFIX}/rococo-museum-docker:latest
    ports:
      - 8093:8093
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      geo.rococo.dc:
        condition: service_healthy
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  painting.rococo.dc:
    container_name: painting.rococo.dc
    image: ${PREFIX}/rococo-painting-docker:latest
    ports:
      - 8095:8095
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      museum.rococo.dc:
        condition: service_healthy
      artist.rococo.dc:
        condition: service_healthy
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  client.rococo.dc:
    container_name: client.rococo.dc
    image: ${PREFIX}/rococo-client-docker:latest
    build:
      context: ./rococo-client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      gateway.rococo.dc:
        condition: service_healthy
    networks:
      - rococo-network

  rococo-e2e-tests:
    profiles: [ test ]
    container_name: rococo-e2e-tests
    image: ${PREFIX}/rococo-e2e-tests:latest
    build:
      context: ./
      dockerfile: ./rococo-e2e-tests/Dockerfile
    environment:
      - ALLURE_DOCKER_API=${ALLURE_DOCKER_API}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BUILD_URL=${BUILD_URL}
      - HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}
      - EXECUTION_TYPE=${EXECUTION_TYPE}
    volumes:
      - ./allure-results:/rococo/rococo-e2e-tests/build/allure-results/
      - ./rococo-e2e-tests/.screen-output/screenshots/selenoid:/rococo/rococo-e2e-tests/.screen-output/screenshots/selenoid
    depends_on:
      client.rococo.dc:
        condition: service_started
    networks:
      - rococo-network

networks:
  rococo-network:
    driver: bridge

volumes:
  mysql-data: