grpc:
  server:
    port: 8094

spring:
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  application:
    name: rococo-geo
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-geo?serverTimezone=UTC&createDatabaseIfNotExist=true'
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: test
    password: secret
  flyway:
    enabled: true
    repair-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rococo-geo
    locations: classpath:db/migration/rococo-geo
    table: flyway_history_geo
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false

logging:
  file:
    path: .logs/rococo-geo/
  level:
    root: INFO
    org.springframework.web: INFO
    org.flywaydb.core: DEBUG
    org.hibernate.SQL: DEBUG